name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello world!"
          echo "Several shell commands in one Run"
          echo "This is last command in this Run"
      - name: Print goodbye
        run: echo "Done - bye!"
